import React from "react"
import { motion } from "framer-motion"
import { skillAnimations } from "../../components/utils"
const { container, item } = skillAnimations
export default function Code() {
  return (
    <motion.svg
      className="absolute"
      variants={container}
      initial="hidden"
      animate="show"
      height="161"
      viewBox="0 0 161 161"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <motion.rect
        variants={item}
        x="39"
        y="46"
        width="21"
        height="10"
        rx="2"
        fill="#27AE60"
      />
      <motion.rect
        variants={item}
        x="70"
        y="26"
        width="21"
        height="10"
        rx="2"
        fill="#27AE60"
      />
      <motion.rect
        variants={item}
        x="122"
        y="76"
        width="21"
        height="10"
        rx="2"
        transform="rotate(180 122 76)"
        fill="#6FCF97"
      />
      <motion.rect
        variants={item}
        x="96"
        y="116"
        width="20"
        height="10"
        rx="2"
        transform="rotate(180 96 116)"
        fill="#BFE0CD"
      />
      <motion.rect
        variants={item}
        x="39"
        y="66"
        width="21"
        height="10"
        rx="2"
        fill="#BFE0CD"
      />
      <motion.rect
        variants={item}
        x="39"
        y="86"
        width="11"
        height="10"
        rx="2"
        fill="#BFE0CD"
      />
      <motion.rect
        variants={item}
        x="85"
        y="86"
        width="12"
        height="10"
        rx="2"
        fill="#219653"
      />
      <motion.rect
        variants={item}
        x="76"
        y="46"
        width="12"
        height="10"
        rx="2"
        fill="#BFE0CD"
      />
      <motion.rect
        variants={item}
        x="63"
        y="66"
        width="21"
        height="10"
        rx="2"
        fill="#6FCF97"
      />
      <motion.rect
        variants={item}
        x="39"
        y="106"
        width="21"
        height="10"
        rx="2"
        fill="#6FCF97"
      />
      <motion.rect
        variants={item}
        x="63"
        y="46"
        width="10"
        height="10"
        rx="2"
        fill="#BFE0CD"
      />
      <motion.rect
        variants={item}
        x="98"
        y="76"
        width="11"
        height="10"
        rx="2"
        transform="rotate(180 98 76)"
        fill="#BFE0CD"
      />
      <motion.rect
        variants={item}
        x="104"
        y="36"
        width="11"
        height="10"
        rx="2"
        transform="rotate(180 104 36)"
        fill="#BFE0CD"
      />
      <motion.rect
        variants={item}
        x="73"
        y="116"
        width="10"
        height="10"
        rx="2"
        transform="rotate(180 73 116)"
        fill="#BFE0CD"
      />
      <motion.rect
        variants={item}
        x="53"
        y="86"
        width="29"
        height="10"
        rx="2"
        fill="#BFE0CD"
      />
      <motion.rect
        variants={item}
        x="100"
        y="86"
        width="20"
        height="10"
        rx="2"
        fill="#6FCF97"
      />
      <motion.rect
        variants={item}
        x="91"
        y="46"
        width="20"
        height="10"
        rx="2"
        fill="#BFE0CD"
      />
      <motion.rect
        variants={item}
        x="40"
        y="26"
        width="28"
        height="10"
        rx="2"
        fill="#BFE0CD"
      />
    </motion.svg>
  )
}
